# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-06 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_userinfo_loggedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='fullname',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
