# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-06 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20170706_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='role',
            field=models.CharField(default='user', max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='fullname',
            field=models.CharField(max_length=100),
        ),
    ]
